### ISSUE TITLE
typer fails to handle star arguments. See argh for reference on how this should behave.

### ISSUE THREAD

**Issue by cottrell** [tiangolo/typer#150]
See here: https://github.com/cottrell/notebooks/tree/master/typer for the simple repro. 

```
#!/usr/bin/env python
import typer

def this(a, *b):
    print(a, b)

if __name__ == '__main__':
    typer.run(this)
```

```shell
$ ./example_with_argh.py a b
a ('b',)
$ ./example_with_argh.py a b c
a ('b', 'c')
$ ./example.py a b
Traceback (most recent call last):
  File "./example.py", line 8, in <module>
    typer.run(this)
  File "/home/cottrell/dev/typer/typer/main.py", line 856, in run
    app()
  File "/home/cottrell/dev/typer/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/cottrell/anaconda3/envs/38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cottrell/anaconda3/envs/38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cottrell/anaconda3/envs/38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cottrell/anaconda3/envs/38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cottrell/dev/typer/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
TypeError: this() got an unexpected keyword argument 'b'
$ ./example.py a b c
Usage: example.py [OPTIONS] A B
Try 'example.py --help' for help.

Error: Got unexpected extra argument (c)
```

**Comment by cottrell** [comment]
I'm not sure what the desired behaviour is but argh is pretty much the best behaviour IMO.

**Comment by tiangolo** [comment]
Thanks for the interest, that's not a feature supported in Click which does the work underneath, so it's not supported in Typer.

Also, Typer is based on type annotations, and in this case, you are not using them. But you could achieve what I think is the same result using type annotations: https://typer.tiangolo.com/tutorial/multiple-values/arguments-with-multiple-values/
