### ISSUE TITLE
[BUG] show-completion and install-completion fail on Windows 7

### ISSUE THREAD

**Issue by richieadler** [tiangolo/typer#155]
### Describe the bug

Using `--show-completion` or `--install-completion` options in Windows 7 fail with a traceback

### To Reproduce

* Create a file `main.py` with:

```Python
import typer

app = typer.Typer()


@app.command()
def hello(name: str):
    typer.echo(f"Hello {name}")


if __name__ == "__main__":
    app()
```

* Call it with:

```bash
python main.py --show-completion
```

* It outputs:

```
Traceback (most recent call last):
  File "C:\temp\1.py", line 11, in <module>
    app()
  File "C:\Prog\Python38-32\lib\site-packages\typer\main.py", line 213, in __call__
    return get_command(self)()
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "C:\Prog\Python38-32\lib\site-packages\click\core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "C:\Prog\Python38-32\lib\site-packages\typer\main.py", line 788, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Prog\Python38-32\lib\site-packages\typer\completion.py", line 59, in show_callback
    shell, _ = shellingham.detect_shell()
  File "C:\Prog\Python38-32\lib\site-packages\shellingham\__init__.py", line 25, in detect_shell
    raise ShellDetectionFailure()
shellingham._core.ShellDetectionFailure
```

* I'm not clear on what the output would be in Windows, I was trying it to find out.

### Expected behavior

Some scripting related to CMD, or a message indicating that the feature is not supported in Windows (7? any?)

### Environment

* OS: Windows 7 (6.1 build 7601 SP1)
* Typer Version 0.3.2
* Python version: 3.8.2

**Comment by tiangolo** [comment]
It's probable that you are trying to do it on `cmd.exe` which doesn't have a way to support completion and is deprecated by Windows: https://support.microsoft.com/en-us/windows/powershell-is-replacing-command-prompt-fdb690cf-876c-d866-2124-21b6fb29a45f

If that's the case, you should use PowerShell instead.
