### ISSUE TITLE
[QUESTION] values argument as dict or json

### ISSUE THREAD

**Issue by sugizo** [tiangolo/typer#219]
### First check

* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the Typer documentation, with the integrated search.
* [x] I already searched in Google "How to X in Typer" and didn't find any information.
* [x] I already searched in Google "How to X in Click" and didn't find any information.

### Description

**objective** 
have values argument as dict or json e.g. {"name": "name2", "strings": 2}

**test.py**
```
@app.command()
def put(tablename, rec_id, values):
    row = db(db[tablename]._id == rec_id).validate_and_update(**values)
    db.commit()
    typer.echo(f"{row.as_dict() }")
```

**execute**
`python3 server.py put instrument 2 {"name": "name2", "strings": 2}`
**result**
`Error: Got unexpected extra arguments (name2, strings: 2})`

**execute**
`python3 server.py put instrument 2 '{"name": "name2", "strings": 2}'`
**result**
```
Traceback (most recent call last):
  File "server.py", line 6, in <module>
    app()
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/sugizo/Downloads/typer/music/exposed/api.py", line 82, in put
    row = db(db[tablename]._id == rec_id).validate_and_update(**values)
TypeError: validate_and_update() argument after ** must be a mapping, not str
```

**question**
how to achieve it in typer ?

### Additional context

typer able to receive argument dict or json type

thanks

**Comment by daddycocoaman** [comment]
Hi, this might sorta go against the idea of Typer focusing on type hints, but _**assuming you trust the data being used**_, this will absolutely work for you:

```python
import ast
import typer

def main(table_name: str, rec_id: int, row: str = typer.Argument(...,callback=ast.literal_eval)):
    print(type(row))

if __name__ == "__main__":
    typer.run(main)
```

```
python.exe typerdict.py sometable 2 "{'id': 2, 'name': 'daddycocoaman'}"
<class 'dict'>
```

**Comment by sugizo** [comment]
another way around
**server.py**
```
@app.command()
def put(tablename, rec_id, raw):
    import json
    values = json.loads(raw)
    row = db(db[tablename]._id == rec_id).validate_and_update(**values)
    db.commit()
    typer.echo(f"{row.as_dict() }")
```

**terminal**
`python server.py put instrument 2 '{"name": "name1", "strings": 1}'`

thanks

**Comment by tiangolo** [comment]
Thanks for the help here @daddycocoaman ! 👏  🙇 

Thanks for reporting back and closing the issue @sugizo  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
