### ISSUE TITLE
Dynamic autocompletion on `typer.Argument

### ISSUE THREAD

**Issue by layoaster** [tiangolo/typer#353]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
# Helper function to get a list of suggestions from an API

def filter_supervisors(status_filter: SupervisorStateFilter, exclude: bool = False) -> list[str]:
    """
    Returns a list of supervisors filtered by statuses.

    :param status_filter: List of status to filter by.
    :param exclude: To make an exclusion filtering, defaults to False.
    :return: Supervisors with a status present in the filter.
    :raises RuntimeError: If there is an issue retrieve
    """
    resp = DruidOverlordApi(
        global_flags.state.druid_router_url, token=global_flags.state.druid_token
    ).supervisor_list(True)

    if resp.status_code != 200:
        raise RuntimeError(
            f"API Error: Can not retrieve a list of supervisors. Error {resp.text}"
        )

    if "ALL" in status_filter:
        return [x["id"] for x in resp.json()]

    if exclude:
        filtered_supervisors = list(filter(lambda x: x["state"] not in status_filter, resp.json()))
    else:
        filtered_supervisors = list(filter(lambda x: x["state"] in status_filter, resp.json()))

    return [x["id"] for x in filtered_supervisors]


# -----------------
# Completion function
def supervisor_names(ctx: typer.Context, incomplete: str) -> Iterator[str]:
    """
    Completion helper for supervisors' names.

    :param ctx: Typer command context to access global flags values.
    :param incomplete: Partial completion substring.
    :return: List of completions.
    """
    if ctx.command.name == "suspend":
        # All supervisor not suspended
        supervisors = filter_supervisors(("SUSPENDED",), True)
    elif ctx.command.name == "resume":
        # All suspended supervisors
        supervisors = filter_supervisors(("SUSPENDED",))
    else:
        # All active supervisors
        supervisors = filter_supervisors(("ALL",))

    for name in supervisors:
        if name.startswith(incomplete):
            yield name

# ----------
# Command autocompletion setup

@app.command(name="get", help="Fetch the current spec of a supervisor")
def get(
    ctx: typer.Context,
    supervisor_name: str = typer.Argument(
        ..., autocompletion=supervisor_names, help="Supervisor id"
    ),
    state: bool = typer.Option(
        False,
        "--state",
        show_default=False,
        help="Display supervisor's current state",
    ),
) -> Optional[int]:
    pass
```

### Description

I'm trying to add dynamic completion for a `typer.Argument` (also tried `typer.Option`)  but the shell completion fails with what seems to be a truncated python stacktrace:

```shell
$ druid-cli supervisor get --supervisor-name …Traceback (most recent call last): 
  File "/home/layo/projects/venv/druid-cli/bin/druid-cli", line 8, in <module>
    sys.exit(app())
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/click/core.py", line 1048, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/core.py", line 468, in _main_shell_completion
    _typer_main_shell_completion(
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/core.py", line 434, in _typer_main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/completion.py", line 155, in shell_complete
    click.echo(comp.complete())
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/_completion_click8.py", line 101, in complete
    completions = self.get_completions(args, incomplete)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/click/shell_completion.py", line 273, in get_completions
    return obj.shell_complete(ctx, incomplete)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/core.py", line 389, in shell_complete
    return _typer_param_shell_complete(self, ctx=ctx, incomplete=incomplete)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/core.py", line 35, in _typer_param_shell_complete
    results = self._custom_shell_complete(ctx, self, incomplete)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/typer/core.py", line 72, in compat_autocompletion
    for c in autocompletion(ctx, [], incomplete):  # type: ignore
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/druid_cli/commands/supervisor.py", line 53, in supervisor_names
    supervisors = filter_supervisors(("ALL",))
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/druid_cli/utils/completion.py", line 20, in filter_supervisors
    resp = DruidOverlordApi(
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/druid_cli/druid/api.py", line 46, in supervisor_list
    return self.request("GET", self._supervisor_url, params={"state": state})
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/druid_cli/utils/http.py", line 52, in request
    return self.session.request(
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/home/layo/projects/venv/druid-cli/lib/python3.9/site-packages/requests/models.py", line 392, in prepare_url

```

By "dynamic" I meant, that I try to fetch the list of completion suggestions calling a REST API. 

If I set a static list of completion suggestions, like used in Typer [docs](https://typer.tiangolo.com/tutorial/options/autocompletion/#custom-completion-for-values), everything works correctly.

Is there any known limitation/issue for my use case? I couldn't find any on Click docs neither.

I couldn't provide a self contained sample code but exceprts of my code.either

### Operating System

Linux

### Operating System Details

Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

### Typer Version

0.4.0

### Python Version

3.9.10

### Additional Context

Using zsh.

Other dependencies versions: 
```
click               8.0.3
shellingham         1.4.0
````

**Comment by ahmetkca** [comment]
I am trying to achieve a similar thing and I found something intereseting. 

if I use `print()` in any part of the autocompletion function it doesn't work. 

I think it has something to do with trying to write to stdout at the sametime.

**Comment by svlandeg** [comment]
Hi! Let me move this thread to the discussion forum (it will stay open there).
