### ISSUE TITLE
[FEATURE] Make typer compatible with PEP 563

### ISSUE THREAD

**Issue by lorddaedra** [tiangolo/typer#43]
### Describe the bug

```
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.8/site-packages/typer/main.py", line 586, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
RuntimeError: Type not yet supported: str
```

https://www.python.org/dev/peps/pep-0563/

### To Reproduce

Add
```
from __future__ import annotations

...
```

**Comment by tiangolo** [comment]
This is now supported as of version `0.2.1` :tada: :rocket:

**Comment by JHaller27** [comment]
Seeing this same issue with typer: 0.3.2 / python 3.9.5 (linux Pop!_OS 20.10 if it matters).

```
  File "/home/{uname}/.local/lib/python3.9/site-packages/typer/main.py", line 587, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
RuntimeError: Type not yet supported: <typer.models.OptionInfo object at 0x7f7ad0d8f640>
```

My code:

```py
import typer

def main(name: typer.Option("world")):
    typer.echo(f"hello {name}")

if __name__ == "__main__":
    typer.run(main)
```

**Comment by wizard-28** [comment]
This does not work anymore

Sample code:

```python
from __future__ import annotations

import typer

app = typer.Typer()


def main():
    app()


@app.command()
def test(flag: list[str] = typer.Option(None, "--flag", "-f", help="A flag")):
    print(flag)


if __name__ == "__main__":
    main()
```

Error:
```python
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    main()
  File "test.py", line 9, in main
    app()
  File "/home/pop-os/.cache/pypoetry/virtualenvs/nala-j_krjJMS-py3.8/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/pop-os/.cache/pypoetry/virtualenvs/nala-j_krjJMS-py3.8/lib/python3.8/site-packages/typer/main.py", line 239, in get_command
    click_command = get_command_from_info(typer_instance.registered_commands[0])
  File "/home/pop-os/.cache/pypoetry/virtualenvs/nala-j_krjJMS-py3.8/lib/python3.8/site-packages/typer/main.py", line 425, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
  File "/home/pop-os/.cache/pypoetry/virtualenvs/nala-j_krjJMS-py3.8/lib/python3.8/site-packages/typer/main.py", line 401, in get_params_convertors_ctx_param_name_from_function
    parameters = get_params_from_function(callback)
  File "/home/pop-os/.cache/pypoetry/virtualenvs/nala-j_krjJMS-py3.8/lib/python3.8/site-packages/typer/utils.py", line 11, in get_params_from_function
    type_hints = get_type_hints(func)
  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

Related issue: https://github.com/tiangolo/typer/issues/371
